force-app/main/default/objects/TriggerConfiguration__mdt/TriggerConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Contains a record for each trigger event so as to enable/disable managed package triggers in a production org.</description>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerConfiguration__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfiguration__mdt/fields/TriggerEvent__c.field-meta.xml
<CustomField>
    <fullName>TriggerEvent__c</fullName>
    <label>Trigger Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandlerFactory.cls
global with sharing class TriggerHandlerFactory {
    global static Map<String, TriggerHandlerFactory> handlerMap = new Map<String, TriggerHandlerFactory>();
    private Map<String, String> triggerClasses = new Map<String, String>();
    private static Map<String, List<TriggerConfiguration__mdt>> configMap = new Map<String, List<TriggerConfiguration__mdt>>();

    static{
        for(TriggerConfiguration__mdt trig : [SELECT Class__c, SObject__c, Order__c, TriggerEvent__c, NamespacePrefix
            FROM TriggerConfiguration__mdt
            WHERE isActive__c = true
            ORDER BY SObject__c, TriggerEvent__c, Order__c]){

            String key = (String.isNotBlank(trig.NamespacePrefix) && trig.SObject__c.contains('__c'))
                ? trig.NamespacePrefix+'__'+trig.SObject__c+'-'+trig.TriggerEvent__c
                : trig.SObject__c+'-'+trig.TriggerEvent__c;
            if(configMap.get(key)==null){
                configMap.put(key, new List<TriggerConfiguration__mdt>());
            }
            configMap.get(key).add(trig);
        }
    }

    global static void run(System.TriggerOperation event) {
        SObjectType soType = (Trigger.isDelete) ? Trigger.old[0].getSObjectType() : Trigger.new[0].getSObjectType();
        String sObjectEvent = soType + '-' + event;
        if (handlerMap.get(sObjectEvent) == null) {
            handlerMap.put(sObjectEvent, new TriggerHandlerFactory(sObjectEvent, soType));
        }
        handlerMap.get(sObjectEvent).execute();
    }

    private TriggerHandlerFactory(String sObjectEvent, SObjectType soType) {
        if(configMap.get(sObjectEvent)!=null){
            for (TriggerConfiguration__mdt var : configMap.get(sObjectEvent)) {
                if(soType == Utils.getObjectWithNamespace(var.SObject__c)){
                    triggerClasses.put(var.Class__c, var.NamespacePrefix);
                }
            }
        }
    }

    private void execute() {
        ITriggerHandler handler;
        TriggerHandlerFactory.Parameter param = new TriggerHandlerFactory.Parameter();
        param.NewSObjects = Trigger.new;
        param.OldSObjectsMap = Trigger.oldMap;
        if(!triggerClasses.isEmpty()){
            for (String cName : triggerClasses.keySet()) {
                handler = getInstance(triggerClasses.get(cName), cName);
                handler.process(param); 
            }
        }
    }

    private ITriggerHandler getInstance(String namespace, String className) {
        ITriggerHandler handler;
        Type cType = (String.isNotBlank(namespace)) ? Type.forName(namespace, className) : Type.forName(className);
        if (cType == null) {
            throw new TriggerServiceException('Error Found in Trigger Handler');
        }
        try {
            handler = (ITriggerHandler) cType.newInstance();
        } catch (Exception e) {
            throw new TriggerServiceException('Error Found in Trigger Handler');
        }
        return handler;
    }

    global class Parameter {
        global List<SObject> NewSObjects {get; set;}
        global Map<Id, SObject> OldSObjectsMap {get; set;}
    }

    global class TriggerServiceException extends Exception {}
}