force-app/main/default/objects/Account/fields/Account_Revenue_Custom_Imp__c.field-meta.xml
<CustomField>
    <fullName>Account_Revenue_Custom_Imp__c</fullName>
    <description>This field is used in the custom implementation apex class to check the &quot;Custom&quot; mode</description>
    <label>Account Revenue Custom Imp</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Custom_Field1__c.field-meta.xml
<CustomField>
    <fullName>Custom_Field1__c</fullName>
    <description>This field is used in account score standard calculation for the mode &quot;Advance&quot;</description>
    <label>Custom Field1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Score_Calculation_Configuration__c/Account_Score_Calculation_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Account Score calculation configuration for admins. Here we can configure for profile, user or org wide configuration</description>
    <label>Account Score Calculation Configuration</label>
</CustomObject>

force-app/main/default/objects/Account_Score_Calculation_Configuration__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <inlineHelpText>Please enter the custom implementation Apex Class name which calculates the account score when the mode value is set as &quot;Custom&quot;, please leave it blank for &quot;Default&quot; or &quot;Advance&quot;.</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Score_Calculation_Configuration__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <inlineHelpText>Please enter only values &quot;Default&quot; or &quot;Advance&quot; or &quot;Custom&quot;</inlineHelpText>
    <label>Mode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&apos;s-Hertogenbosch</fullName>
            </value>
            <value>
                <fullName>Alkmaar</fullName>
            </value>
            <value>
                <fullName>Almelo</fullName>
            </value>
            <value>
                <fullName>Almere Stad</fullName>
            </value>
            <value>
                <fullName>Alphen aan den Rijn</fullName>
            </value>
            <value>
                <fullName>Amersfoort</fullName>
            </value>
            <value>
                <fullName>Amstelveen</fullName>
            </value>
            <value>
                <fullName>Amsterdam</fullName>
            </value>
            <value>
                <fullName>Amsterdam-Zuidoost</fullName>
            </value>
            <value>
                <fullName>Apeldoorn</fullName>
            </value>
            <value>
                <fullName>Arnhem</fullName>
            </value>
            <value>
                <fullName>Breda</fullName>
            </value>
            <value>
                <fullName>Delft</fullName>
            </value>
            <value>
                <fullName>Deventer</fullName>
            </value>
            <value>
                <fullName>Dordrecht</fullName>
            </value>
            <value>
                <fullName>Eindhoven</fullName>
            </value>
            <value>
                <fullName>Enschede</fullName>
            </value>
            <value>
                <fullName>Gouda</fullName>
            </value>
            <value>
                <fullName>Groningen</fullName>
            </value>
            <value>
                <fullName>Haarlem</fullName>
            </value>
            <value>
                <fullName>Heerlen</fullName>
            </value>
            <value>
                <fullName>Helmond</fullName>
            </value>
            <value>
                <fullName>Hengelo</fullName>
            </value>
            <value>
                <fullName>Hilversum</fullName>
            </value>
            <value>
                <fullName>Hoofddorp</fullName>
            </value>
            <value>
                <fullName>Hoorn</fullName>
            </value>
            <value>
                <fullName>Leeuwarden</fullName>
            </value>
            <value>
                <fullName>Leiden</fullName>
            </value>
            <value>
                <fullName>Lelystad</fullName>
            </value>
            <value>
                <fullName>Maastricht</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    /**
     * Account Creation for test data
     */
    public static Account accountCreation() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.AnnualRevenue = 1000;
        acc.BillingStreet = 'Str 2';
        acc.BillingState = 'North Holland';
        acc.BillingCity = 'Amsterdam';
        acc.BillingCountry = 'Netherlands';
        acc.BillingPostalCode = '1017 CJ';
        //acc.Custom_Field1__c = 2000;
        //acc.Account_Revenue_Custom_Imp__c = 2500;
        insert acc;

        return acc;
    }

    /**
     * Custom setting creation for test data
     * @param{mode} - pass the  account score calculation mode
     * @param{apexClass} - pass the apex class name for custom mode calculation
     */
    /*public static void modeCustomDettingCreation(String mode, String apexClass) {
        Account_Score_Calculation_Configuration__c modeCustomDetting = new Account_Score_Calculation_Configuration__c();
        modeCustomDetting.Mode__c = mode;
        modeCustomDetting.Apex_Class_Name__c = String.isNotBlank(apexClass) ? apexClass : '';
        insert modeCustomDetting;
    }*/

    /**
     * User Creation for test data
     * @param{profName} - pass the profile name
     * @param{email} - pass the email addres
     */
    public static User createUser(String profName, String email){
        Profile p = [SELECT Id FROM Profile WHERE Name=: profName];
        String uniqueUserName = 'userName' + DateTime.now().getTime() + '@DevUserName.com';
        
        User u = new User(Alias = 'devUser', Email= email,
            EmailEncodingKey='UTF-8', LastName='Dev', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName=uniqueUserName);
        insert u;

        return u;
    }

    /**
     * Query User for test data
     * @param{aliasName} - pass the user alias name
     */
    public static User queryUserBasedOnAlias(String aliasName){
        return [Select Id FROM User WHERE Alias =:aliasName LIMIT 1];
    }

    /***
     * Supplier Creation
     */

    public static Supplier__c supplierCreation(integer i) {
        Supplier__c supp = new Supplier__c();
        supp.Name = 'Test '+ i;
        supp.City__c = 'Amsterdam';
        supp.Country__c = '';
        supp.State__c = 'North Holland';
        supp.Street__c = 'Herengracht 574';
        supp.PostalCode__c = '1017 CJ';

        return supp;
    }

    /***
     * Case Creation
     */

    public static Case caseCreation(Integer i, Id accId) {
        Case cas = new Case();
        cas.Subject = 'Test '+ i;
        cas.AccountId = accId;
        cas.Status = 'New';
        return cas;
    }
}